name: 'Secrets for AppSettings.json'
description: 'Use secrets.json to update appsettings.json'
inputs:
  secrets:  # id of input
    description: 'Content of secrets.json'
    required: true
    default: '{}'
  appsettings:  # id of input
    description: 'Path to appsettings.json'
    required: true
    default: 'appsettings.json'
  version:  # id of input
    description: 'Build version'
    required: false
  date:  # id of input
    description: 'Build date'
    required: false
  timestamp:  # id of input
    description: 'Build timestamp'
    required: false
  flavor:  # id of input
    description: 'Build flavor, such as windows,ios,macos'
    required: false
    default: 'windows'
runs:
  using: 'node20'
  main: 'dist/index.js'
