name: 'Secrets for AppSettings.json'
description: 'Use secrets.json to update appsettings.json'
inputs:
  secrets:  # id of input
    description: 'Content of secrets.json'
    required: true
    default: '{}'
  appsettings:  # id of input
    description: 'Path to appsettings.json'
    required: true
    default: 'appsettings.json'
  flavor:  # id of input
    description: 'Build flavor, such as windows,ios,macos'
    required: false
    default: 'windows'
  version:  # id of input
    description: 'Build version repository variable name'
    required: false
    default: 'BuildVersion'
  date:  # id of input
    description: 'Build date repository variable name'
    required: false
    default: 'BuildDate'
  timestamp:  # id of input
    description: 'Build timestamp repository variable name'
    required: false
    default: 'BuildTimeStamp'

runs:
  using: 'node20'
  main: 'dist/index.js'
