name: 'Secrets for AppSettings.json'
description: 'Use secrets.json to update appsettings.json'
inputs:
  secrets:  # id of input
    description: 'Content of secrets.json'
    required: true
    default: '{}'
  appsettings:  # id of input
    description: 'Path to appsettings.json'
    required: true
    default: 'appsettings.json'
runs:
  using: 'node20'
  main: 'dist/index.js'
