name: 'Secrets for AppSettings.json'
description: 'Use secrets.json to update appsettings.json'
inputs:
  secrets:  # id of input
    description: 'Content of secrets.json'
    required: true
    default: '{}'
  appsettings:  # id of input
    description: 'Path to appsettings.json'
    required: false
    default: 'appsettings.json'
  csproj:
    description: 'Path to csproj file'
    required: false
  manifest:
    description: 'Path to Windows Package.appxmanifest file'
    required: false
    default: 'Package.appxmanifest'
  printFile:
    description: 'Print file content after replacement (secrets are hidden)'
    required: false
    default: false
  buildversion:  # id of input
    description: 'Build version repository variable value'
    required: false
    default: '0.0.0'
  buildflavor:  # id of input
    description: 'Build flavor, such as windows,ios,macos'
    required: false
    default: 'windows'
  version:  # id of input
    description: 'Build version repository variable name'
    required: false
    default: 'BuildVersion'
  date:  # id of input
    description: 'Build date repository variable name'
    required: false
    default: 'BuildDate'
  timestamp:  # id of input
    description: 'Build timestamp repository variable name'
    required: false
    default: 'BuildTimeStamp'
outputs:
  version: # id of output
    description: 'Build version from tag'
  date: # id of output
    description: 'Build date string'
  timestamp: # id of output
    description: 'Build unix timestamp'

runs:
  using: 'node20'
  main: 'dist/index.js'
