on:
  push:
    tags:
      - '*'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Check out current repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Update Secrets in AppSettings.json
      id: info
      uses: Reality-Check-Inc/secrets-json-action@v1.9.34
      with:
        secrets: ${{ secrets.SECRETS_JSON }}
        appsettings: test_data/appsettings.json
        buildflavor: macOS
      env:
        GH_TOKEN: ${{ secrets.PAT }}

    # By default, Linux runners use the bash shell,
    # so you must use the syntax $NAME.
    # By default, Windows runners use PowerShell,
    # so you would use the syntax $env:NAME
    # Use the output from the `info` step
    - name: Set variables
      run: |
        echo "BUILD_VERSION=$(echo ${{ steps.info.outputs.version }})" >> $GITHUB_ENV
        echo "BUILD_TIMESTAMP=$(echo ${{ steps.info.outputs.timestamp }})" >> $GITHUB_ENV
        echo "BUILD_DATE=$(echo ${{ steps.info.outputs.date }})" >> $GITHUB_ENV

    - name: Show the variables
      run: |
        echo $BUILD_VERSION
        echo $BUILD_TIMESTAMP
        echo $BUILD_DATE
