name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15

    steps:

    - name: "Update Secrets in AppSettings.json"
      uses: Reality-Check-Inc/secrets-json-action@v0.1
      with:
        secrets: {}
        appsettings: test_data/appsettings.json
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
