name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15

    steps:
      uses: Reality-Check-Inc/secrets-json-action@v0.1
        secrets: "{}"
        appsettings: "package.json"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
