name: CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15

    steps:

    - name: "Update Secrets in AppSettings.json"
      uses: Reality-Check-Inc/secrets-json-action@v0.7
      with:
        secrets: ${{ secrets.SECRETS_JSON }}
        appsettings: ./test_data/appsettings.json
