name: CI

on:
  push:
    branches: [ "main" ]
    tags-ignore:
      - '**'

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15

    steps:
    - name: Check out current repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: repository variable list
      run: |
          gh variable list
      env:
        GH_TOKEN: ${{ secrets.PAT }}

    - name: Update Secrets in AppSettings.json
      uses: Reality-Check-Inc/secrets-json-action@v0.42
      with:
        secrets: ${{ secrets.SECRETS_JSON }}
        appsettings: test_data/appsettings.json
        flavor: Windows
      env:
        GH_TOKEN: ${{ secrets.PAT }}
